# Generated by Django 3.1.2 on 2020-11-27 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=20, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email-адрес')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
