# Generated by Django 3.1.2 on 2020-11-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleBoard', '0002_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Проверена', 'Проверена'), ('Требует исправлений', 'Требует исправлений'), ('Ожидает проверки', 'Ожидает проверки')], default='C', max_length=20, verbose_name='Статус'),
        ),
    ]
