# Generated by Django 3.1.2 on 2020-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleBoard', '0004_auto_20201130_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(upload_to='', verbose_name='Документ'),
        ),
    ]
