# Generated by Django 3.1.2 on 2020-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleBoard', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('A', 'Проверена'), ('B', 'Требует исправлений'), ('C', 'Ожидает проверки')], default='C', max_length=20, verbose_name='Статус'),
        ),
    ]
